server:
  port: 8090

build.name: @project.name@
build.version: @project.version@

#DB_HOSTNAME=localhost;DB_PORT=3306;DB_NAME=abc_tech;DB_USERNAME=root;DB_PASSWORD=Fiap1234

spring:
  datasource:
    url: jdbc:mysql://${DB_HOSTNAME}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create